# Generated by Django 5.2.4 on 2025-07-14 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=255)),
                ('universidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=150)),
                ('persona_contacto', models.CharField(max_length=255)),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('HIRING_GROUP', 'Hiring Group'), ('EMPRESA', 'Empresa'), ('POSTULANTE', 'Postulante'), ('CONTRATADO', 'Contratado')], default='POSTULANTE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_contratacion', models.CharField(choices=[('1 mes', '1 Mes'), ('6 meses', '6 Meses'), ('1 año', '1 Año'), ('indefinido', 'Indefinido')], max_length=20)),
                ('salario_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('tipo_sangre', models.CharField(blank=True, max_length=5, null=True)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=30, null=True)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrataciones', to='api.banco')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='api.candidatoprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('año', models.IntegerField()),
                ('total_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='api.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'mes', 'año')},
            },
        ),
        migrations.CreateModel(
            name='DetalleNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('contratacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_nomina', to='api.contratacion')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.nomina')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_nomina_como_empleado', to='api.usuario')),
            ],
            options={
                'unique_together': {('nomina', 'empleado')},
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inactivacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='api.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('contratado', 'Contratado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='api.oferta')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='api.usuario')),
            ],
            options={
                'unique_together': {('oferta', 'postulante')},
            },
        ),
        migrations.AddField(
            model_name='contratacion',
            name='postulacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contratacion', to='api.postulacion'),
        ),
        migrations.CreateModel(
            name='ReciboPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('año', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('detalle_nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos_pago', to='api.detallenomina')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='candidatoprofile',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidato_profile', to='api.usuario'),
        ),
    ]
