# Generated by Django 5.2.4 on 2025-07-13 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=255)),
                ('universidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('HIRING_GROUP', 'Hiring Group'), ('EMPRESA', 'Empresa'), ('POSTULANTE', 'Postulante'), ('CONTRATADO', 'Contratado')], default='POSTULANTE', max_length=50)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('candidato_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='api.candidatoprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=150)),
                ('persona_contacto', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_profile', to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='candidatoprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidato_profile', to='api.usuario'),
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion_requerida', models.CharField(max_length=255)),
                ('cargo_vacante', models.CharField(max_length=255)),
                ('descripcion_perfil', models.TextField()),
                ('salario_ofrecido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to='api.empresaprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('duracion', models.CharField(max_length=100)),
                ('salario_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banco', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=20)),
                ('candidato_contratado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='api.usuario')),
                ('vacante_aplicada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.vacante')),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='api.usuario')),
                ('vacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='api.vacante')),
            ],
            options={
                'unique_together': {('candidato', 'vacante')},
            },
        ),
    ]
