# Generated by Django 5.2.4 on 2025-07-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatoprofile',
            name='pais',
            field=models.CharField(default='No especificado', max_length=100),
        ),
    ]
