# Generated by Django 5.2.4 on 2025-07-20 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_candidatoprofile_pais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencialaboral',
            old_name='candidato',
            new_name='candidato_profile',
        ),
        migrations.CreateModel(
            name='InformacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(max_length=255)),
                ('universidad', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('candidato_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_personal', to='api.candidatoprofile')),
            ],
        ),
    ]
